"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.warnDeprecation = exports.checkCompatEnabled = exports.generateCodeFrame = exports.getConstantType = exports.processSlotOutlet = exports.buildDirectiveArgs = exports.buildProps = exports.resolveComponentType = exports.transformElement = exports.trackSlotScopes = exports.trackVForSlotScopes = exports.buildSlots = exports.stringifyExpression = exports.processExpression = exports.transformExpression = exports.createForLoopParams = exports.processFor = exports.processIf = exports.noopDirectiveTransform = exports.transformBind = exports.transformOn = exports.transformModel = exports.getBaseTransformPreset = exports.createCompilerError = exports.generate = exports.createStructuralDirectiveTransform = exports.traverseNode = exports.createTransformContext = exports.transform = exports.baseParse = exports.baseCompile = void 0;
var compile_1 = require("./compile");
Object.defineProperty(exports, "baseCompile", { enumerable: true, get: function () { return compile_1.baseCompile; } });
var parse_1 = require("./parse");
Object.defineProperty(exports, "baseParse", { enumerable: true, get: function () { return parse_1.baseParse; } });
var transform_1 = require("./transform");
Object.defineProperty(exports, "transform", { enumerable: true, get: function () { return transform_1.transform; } });
Object.defineProperty(exports, "createTransformContext", { enumerable: true, get: function () { return transform_1.createTransformContext; } });
Object.defineProperty(exports, "traverseNode", { enumerable: true, get: function () { return transform_1.traverseNode; } });
Object.defineProperty(exports, "createStructuralDirectiveTransform", { enumerable: true, get: function () { return transform_1.createStructuralDirectiveTransform; } });
var codegen_1 = require("./codegen");
Object.defineProperty(exports, "generate", { enumerable: true, get: function () { return codegen_1.generate; } });
var errors_1 = require("./errors");
Object.defineProperty(exports, "createCompilerError", { enumerable: true, get: function () { return errors_1.createCompilerError; } });
__exportStar(require("./ast"), exports);
__exportStar(require("./utils"), exports);
__exportStar(require("./babelUtils"), exports);
__exportStar(require("./runtimeHelpers"), exports);
var compile_2 = require("./compile");
Object.defineProperty(exports, "getBaseTransformPreset", { enumerable: true, get: function () { return compile_2.getBaseTransformPreset; } });
var vModel_1 = require("./transforms/vModel");
Object.defineProperty(exports, "transformModel", { enumerable: true, get: function () { return vModel_1.transformModel; } });
var vOn_1 = require("./transforms/vOn");
Object.defineProperty(exports, "transformOn", { enumerable: true, get: function () { return vOn_1.transformOn; } });
var vBind_1 = require("./transforms/vBind");
Object.defineProperty(exports, "transformBind", { enumerable: true, get: function () { return vBind_1.transformBind; } });
var noopDirectiveTransform_1 = require("./transforms/noopDirectiveTransform");
Object.defineProperty(exports, "noopDirectiveTransform", { enumerable: true, get: function () { return noopDirectiveTransform_1.noopDirectiveTransform; } });
var vIf_1 = require("./transforms/vIf");
Object.defineProperty(exports, "processIf", { enumerable: true, get: function () { return vIf_1.processIf; } });
var vFor_1 = require("./transforms/vFor");
Object.defineProperty(exports, "processFor", { enumerable: true, get: function () { return vFor_1.processFor; } });
Object.defineProperty(exports, "createForLoopParams", { enumerable: true, get: function () { return vFor_1.createForLoopParams; } });
var transformExpression_1 = require("./transforms/transformExpression");
Object.defineProperty(exports, "transformExpression", { enumerable: true, get: function () { return transformExpression_1.transformExpression; } });
Object.defineProperty(exports, "processExpression", { enumerable: true, get: function () { return transformExpression_1.processExpression; } });
Object.defineProperty(exports, "stringifyExpression", { enumerable: true, get: function () { return transformExpression_1.stringifyExpression; } });
var vSlot_1 = require("./transforms/vSlot");
Object.defineProperty(exports, "buildSlots", { enumerable: true, get: function () { return vSlot_1.buildSlots; } });
Object.defineProperty(exports, "trackVForSlotScopes", { enumerable: true, get: function () { return vSlot_1.trackVForSlotScopes; } });
Object.defineProperty(exports, "trackSlotScopes", { enumerable: true, get: function () { return vSlot_1.trackSlotScopes; } });
var transformElement_1 = require("./transforms/transformElement");
Object.defineProperty(exports, "transformElement", { enumerable: true, get: function () { return transformElement_1.transformElement; } });
Object.defineProperty(exports, "resolveComponentType", { enumerable: true, get: function () { return transformElement_1.resolveComponentType; } });
Object.defineProperty(exports, "buildProps", { enumerable: true, get: function () { return transformElement_1.buildProps; } });
Object.defineProperty(exports, "buildDirectiveArgs", { enumerable: true, get: function () { return transformElement_1.buildDirectiveArgs; } });
var transformSlotOutlet_1 = require("./transforms/transformSlotOutlet");
Object.defineProperty(exports, "processSlotOutlet", { enumerable: true, get: function () { return transformSlotOutlet_1.processSlotOutlet; } });
var hoistStatic_1 = require("./transforms/hoistStatic");
Object.defineProperty(exports, "getConstantType", { enumerable: true, get: function () { return hoistStatic_1.getConstantType; } });
var shared_1 = require("@vue/shared");
Object.defineProperty(exports, "generateCodeFrame", { enumerable: true, get: function () { return shared_1.generateCodeFrame; } });
// v2 compat only
var compatConfig_1 = require("./compat/compatConfig");
Object.defineProperty(exports, "checkCompatEnabled", { enumerable: true, get: function () { return compatConfig_1.checkCompatEnabled; } });
Object.defineProperty(exports, "warnDeprecation", { enumerable: true, get: function () { return compatConfig_1.warnDeprecation; } });
